### ISSUE TITLE
yagmail error

### ISSUE THREAD

**Issue by adamc199** [OpenVoiceOS/skill-ovos-dictation#1]
I'm relatively new to Mycroft and python. Very new to JSON

This is the error I'm getting:
`12:19:18.295 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Dictation Skill
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 598, in wrapper
handler(message)
File "/opt/mycroft/skills/skill-dictation.jarbasal/__init__.py", line 125, in handle_stop_dictation_intent
self.send()
File "/opt/mycroft/skills/skill-dictation.jarbasal/__init__.py", line 140, in send
yag.send(self.target_email, title, body)
AttributeError: 'DictationSkill' object has no attribute 'target_email'
`

Here is my conf file, which vaildates. (username & password xxx-d out)

`{  
   "tts":{  
      "module":"mimic",
      "mimic":{  
         "voice":"ap",
         "path":"/usr/local/bin/mimic"
      }
   },
   "listener":{  
      "sampl_rate":16000,
      "channels":1,
      "record_wake_words":false,
      "record_utterances":false,
      "phoneme_duration":800,
      "multiplier":1.9,
      "energy_ratio":1.5,
      "wake_word":"hey douglas",
      "phonemes":"HH EY . D AH G L AH S .",
      "stand_up word":"wake up"
   },
   "email":{  
      "email":"xxxx@gmail.com",
      "password":"xxxx",
      "destinatary":"adam@curry.com"
   }
}`

I do not get an error loading the conf file upon startup, but email fails.

Without the email config in the conf file the skill works fine through the built-in send_email function

**Comment by adamc199** [comment]
I think I found the error.

IN __init__.py line 37:
self.target_mail = mail_config.get("destinatary", self.email)

defines selt.target_mail

But in line 140:
yag.send(self.target_email, title, body)

send.target_email is used and throws an error because it is not defined.

I changed the def and it now works.

Great skill, thanks for making it!

AC
